FROM apache/airflow:2.8.1-python3.8


COPY ./requirements_airflow.txt /
RUN pip install -r /requirements_airflow.txt

# RUN pip install --no-cache-dir -r requirements.txt

# CMD ["python", "/opt/airflow/pythonscripts/client.py"]